window.PENGYN_CATALOG = (() => {
const niches=[
['ALI','Alimentação','Restaurantes, cafés e negócios de refeições','Terracota, creme e verde oliva','Não atende automaticamente doces, bebidas ou dietas específicas. Evitar pratos de um único segmento.',[
'Mesa acolhedora com louça neutra, guardanapo de linho e ingredientes ao fundo','Close de ervas frescas, tomate e azeite em bancada limpa','Mãos lavando vegetais frescos antes do preparo','Ingredientes organizados por cor em uma bancada de cozinha','Mãos finalizando uma preparação, enquadramento sem prato identificável','Detalhe de textura de ingredientes frescos com luz lateral','Pessoa apreciando o aroma de uma refeição, prato fora do foco','Duas pessoas compartilhando uma mesa sem pratos específicos em destaque','Mesa pequena cuidadosamente preparada para uma pausa','Organização de ingredientes em recipientes neutros','Composição de louça, talheres e guardanapos pronta para receber','Mesa posta junto à janela com cadeira livre e atmosfera convidativa']],
['BEL','Beleza e autocuidado','Espaços de beleza, cosméticos e autocuidado','Areia, rosé suave e branco','Evitar procedimentos, antes/depois e promessas de resultado. Não representa todas as especialidades.',[
'Ambiente acolhedor com espelho, toalhas e luz natural','Close de textura cremosa sobre superfície neutra','Mãos organizando toalhas limpas e acessórios de cuidado','Composição de frascos sem rótulos e tecido macio','Mãos preparando uma bancada de autocuidado','Detalhe de toalha, vidro fosco e acabamento de cerâmica','Pessoa relaxando em ambiente de autocuidado, expressão natural','Momento de pausa com vela apagada, toalha e vegetação','Composição simples de rotina com poucos produtos neutros','Objetos de cuidado alinhados em bancada limpa','Espaço preparado com toalha dobrada e assento confortável','Ambiente de cuidado com luz suave e espaço acolhedor']],
['MOD','Moda e acessórios','Lojas de roupas e acessórios de estilo casual','Grafite, off-white e caramelo','Peças ilustrativas podem não existir na loja. Evitar modelos, marcas e estilos muito específicos.',[
'Composição editorial de tecidos neutros com acessório discreto','Close de trama de tecido e costura bem definida','Mãos selecionando tecidos em uma arara de cores neutras','Flat lay com roupa básica, bolsa e acessório sem marca','Mãos organizando peças em bancada de loja','Detalhe de acabamento de bolsa e textura de tecido','Pessoa com look casual neutro caminhando em cenário urbano','Duas combinações de cores em tecidos lado a lado','Acessório discreto em composição com roupa básica','Peças dobradas e organizadas por tonalidade','Embalagem de papel sem marca com tecido aparecendo','Arara de loja organizada em espaço claro e convidativo']],
['CAS','Casa e decoração','Decoração, organização e artigos para casa','Bege, madeira e verde sálvia','Não apresentar como imóvel, produto ou projeto real do cliente. Evitar mobiliário muito singular.',[
'Canto de sala acolhedor com planta, tecido e madeira','Close de textura de linho e cerâmica artesanal neutra','Mãos organizando objetos em uma prateleira','Composição de almofada, vaso e manta em cores harmônicas','Mãos ajustando uma manta em um sofá','Detalhe de junção de madeira e tecido em luz natural','Pessoa lendo em um canto confortável da casa','Mesa lateral organizada com livro e planta','Pequeno espaço bem aproveitado com cesto e prateleira','Objetos domésticos agrupados por função em bancada','Ambiente arrumado com luz da manhã e poucos elementos','Entrada de casa acolhedora com planta e iluminação suave']],
['SER','Serviços profissionais','Consultoria e serviços administrativos ou comerciais','Azul profundo, cinza e branco','Não representa profissões técnicas específicas. Evitar certificados, métricas e resultados fictícios.',[
'Ambiente de atendimento organizado com mesa e duas cadeiras','Close de caderno, caneta e materiais de trabalho neutros','Mãos anotando necessidades em reunião sem texto legível','Mesa com organização visual de etapas em cartões em branco','Duas pessoas discutindo uma tarefa com notebook sem dados','Detalhe de agenda e organização de documentos sem conteúdo','Pessoa trabalhando com foco em espaço claro','Conversa acolhedora entre profissional e cliente em cena ilustrativa','Mesa simplificada com poucos instrumentos de trabalho','Mãos conferindo documentos sem números ou texto legível','Ambiente de trabalho preparado para uma reunião','Mesa com cadeira livre em espaço de atendimento convidativo']],
['BEM','Bem-estar e movimento','Atividade física leve, yoga e hábitos de bem-estar','Verde suave, areia e azul claro','Não atende todo esporte ou serviço de saúde. Evitar cura, transformação corporal e exercícios arriscados.',[
'Pessoa caminhando em parque com postura natural','Close de tênis neutro, toalha e garrafa sem marca','Pessoa preparando um tapete para alongamento leve','Composição de itens para uma rotina ativa simples','Pessoa fazendo alongamento suave em ambiente tranquilo','Detalhe de tapete, tecido e luz natural','Pessoa descansando após caminhada com expressão tranquila','Duas pessoas caminhando juntas em área verde','Garrafa de água e toalha em pausa de atividade','Itens de atividade leve organizados junto a uma janela','Espaço aberto preparado para prática leve','Caminho arborizado iluminado convidando ao movimento']],
['PET','Pets e cuidados','Negócios de cuidados e artigos para cães e gatos','Creme, azul suave e amarelo discreto','Coleção limitada a cães e gatos. Evitar procedimentos veterinários e produtos específicos.',[
'Cão e gato tranquilos em ambiente doméstico acolhedor','Close de pata sobre manta macia','Mãos organizando escova e toalha para cuidado de pet','Composição de brinquedos neutros para cães e gatos','Pessoa escovando suavemente um cão em cena natural','Detalhe de manta, brinquedo e comedouro sem marca','Pet descansando confortavelmente em cama limpa','Pessoa brincando com gato em casa','Passeio tranquilo com cão e guia comum','Itens de pet limpos e organizados em cesto','Canto de descanso preparado com água e manta','Pet olhando curioso em ambiente claro e acolhedor']],
['AUT','Automotivo','Estética, limpeza e cuidados gerais com automóveis','Grafite, prata e azul profundo','Não serve para toda manutenção mecânica. Evitar marcas, placas e peças técnicas específicas.',[
'Automóvel genérico limpo em ambiente de cuidado automotivo','Close de reflexo natural em pintura sem emblema','Mãos organizando panos de microfibra e escovas','Composição de materiais de limpeza sem marcas','Mãos limpando cuidadosamente uma superfície externa','Detalhe de acabamento limpo de painel sem marca','Interior de carro organizado e iluminado naturalmente','Pessoa observando veículo limpo em cena ilustrativa','Pano macio e água em composição de cuidado simples','Materiais alinhados em bancada limpa de trabalho','Veículo genérico pronto em espaço organizado','Detalhe de porta aberta em carro limpo e acolhedor']],
['EDU','Educação e aprendizado','Cursos livres, aulas e apoio ao estudo','Azul, branco e amarelo suave','Não cobre disciplinas específicas. Evitar diplomas, notas e aprovação garantida.',[
'Pessoa estudando em mesa organizada com luz natural','Close de livro aberto sem texto legível e lápis','Mãos preparando materiais antes do estudo','Caderno, cartões em branco e livros organizados','Duas pessoas explorando uma atividade de aprendizagem','Detalhe de lápis e anotações desfocadas em caderno','Pessoa concentrada aprendendo com notebook sem conteúdo legível','Pequeno grupo de adultos colaborando em ambiente de estudo','Mesa com uma tarefa simples e materiais essenciais','Materiais de estudo separados em pequenas etapas','Espaço de aprendizado preparado com assento livre','Caderno aberto e cadeira em ambiente convidativo ao estudo']],
['TEC','Tecnologia e digital','Serviços digitais, informática e suporte geral','Azul profundo, grafite e ciano discreto','Não cobre qualquer produto tecnológico. Evitar interfaces falsas legíveis, marcas e segurança garantida.',[
'Estação de trabalho digital moderna e organizada','Close de teclado e acabamento de notebook sem marca','Mãos organizando cabos e dispositivos sobre bancada','Notebook, mouse e smartphone com telas neutras','Profissional analisando dispositivo em cena ilustrativa','Detalhe de conexões e materiais eletrônicos plausíveis','Pessoa usando tecnologia em rotina de trabalho tranquila','Duas pessoas colaborando com notebook de tela neutra','Mesa digital simples com poucos dispositivos','Cabos e acessórios organizados por função','Estação de trabalho pronta com tela abstrata sem dados','Ambiente digital claro com cadeira livre e luz natural']]
];

return {checkoutEndpoint: "", allowedCheckoutHosts: [], collections: niches.map(n => ({code:n[0],name:n[1],description:n[2],compatibility:n[4],colors: ["#c5b9ac","#8b9e94","#cec0e1"],available:false,images:[],roles:["Atração","Desejo","Confiança","Inspiração","Processo","Qualidade","Benefício","Conexão","Utilidade","Cuidado","Consideração","Convite"]}))}; })();
